# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('hashtag', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hashtag',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
