# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20161015_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
    ]
